### ISSUE TITLE
Super-Sampled AA Player Light Flickering 

### ISSUE THREAD

**Issue by 9mmdose** [OpenStarbound/OpenStarbound#117]
Possibily related to #104  
not sure what really causes it

https://github.com/user-attachments/assets/1c256a0c-b96c-4602-9daa-6465449b9a85

**Comment by Elysium037** [comment]
Late comment but I have found the answer
The flickering occurs due to some sort of conflict with the Neki race, specifically the NekiFU mod, which enables a race-specific night-vision passive ability which generates a light source at the player's position. I am not exactly sure what happens for the flickering to occur, but I do know that it does not happen in vanilla Starbound, and it only happens with the Neki, and with the NekiFU mod. It does not relate to OpenStarbound's Super-Sampled AA or new lighting. I suggest not using that mod at the very least from now on, or using NekiShades, a mod by the same developer of NekiFU and the Neki race, which disables the nightvision. A comment from the mod page on Steam depicts the issue on OpenStarbound, from the user Boooo, quoting:
"There is a bug in Openstarbound where neki's night vision will flicker a lot from frame to frame when the frame rate drops below 52. This mod will hopefully fix that. And it worked out well. Applause :)"
I know this is a really late reply but I hope this solves the confusion.
